### ISSUE TITLE
[14.0] sale_layout_category_hide_detail: Display subtotal title in a better manner

### ISSUE THREAD

**Issue by rousseldenis** [OCA/sale-reporting#177]
@victoralmau @pedrobaeza 

During supersedes of https://github.com/OCA/sale-reporting/pull/170, you did not attend comment about subtotal text mentioned in https://github.com/OCA/sale-reporting/pull/128.

Could we improve that ?

**Comment by pedrobaeza** [comment]
Which one do you refer? Can you please put it here in the issue for not having to look cross-references?
