### ISSUE TITLE
Availability for version 16

### ISSUE THREAD

**Issue by exposure-admin** [OCA/sale-reporting#225]
Will this be migrated to version 16?, If yes. What's the planning for it?

**Comment by pedrobaeza** [comment]
Check https://github.com/OCA/sale-reporting/issues/174 for the migration progress.

No deadlines, unless you fund the migration of any of the modules to the contributor of your choice.

**Comment by exposure-admin** [comment]
Hello Pedro and others.

I would like to have the module: sale_layout_category_hide_detail migrated. I see the migration is already in progress.
How much funding would be needed to get it finished by August 3th.

Regards,

Remco

**Comment by pedrobaeza** [comment]
Hi @exposure-admin, for this time, there's no need of that, as https://github.com/OCA/sale-reporting/pull/222 is almost finished and it will be merged in the next days. Consider to fund other OCA migrations for enriching even more the 16.0 ecosystem.
