### ISSUE TITLE
[16] sale_report_delivered - Sales standard report lost when installing the module

### ISSUE THREAD

**Issue by Gelojr** [OCA/sale-reporting#236]
## Module
sale_report_delivered
## Describe the bug
The default sales report is lost when the module is installed.
## To Reproduce
**Affected versions**:
16 at least

1. Before installing the module sale_report_delivered, review the default sales report. It is not accessed from a submenu, but from the Sales Report menu.
![image](https://github.com/OCA/sale-reporting/assets/147538094/bf70aef3-10cc-47a4-8235-8ac986ec8b59)
2. Install the module sale_report_delivered
3. When you click on the Sales Reporting menu, the "Sales from deliveries" submenu appears, but you have lost access to the default report.
![image](https://github.com/OCA/sale-reporting/assets/147538094/9eeaa143-01cf-4d34-8d9e-b30bab23d811)
![image](https://github.com/OCA/sale-reporting/assets/147538094/42aa0d11-03e9-4cde-9958-75700dcf62e8)
https://www.loom.com/share/5cb44d89b41b4d2bad0238d3e188fb18?sid=ae8ef319-9d5d-4538-88a7-8f82dc6b8fae

**Expected behavior**
Clicking on the Report menu should display the 2 reports. The standard report and the Sales from Deliveries report.

@sergio-teruel 
@moduon MT-3600

**Comment by sergio-teruel** [comment]
Hi @Gelojr This is a fail of Odoo only in v16

this is de PR for Odoo:
https://github.com/odoo/odoo/pull/139253

**Comment by Gelojr** [comment]
Hi @sergio-teruel ,
Thanks for your contribution 👍
