### ISSUE TITLE
[8.0] Sale Order Total amount minus delivered

### ISSUE THREAD

**Issue by rafaelbn** [OCA/sale-reporting#31]
Hi all,

I would like to ask about real information in sale orders about which amount of them is really pending to invoices.

Let say you sell 100 iMacs, then you will earn 160.000€ because each iMac cost 1600€. Then you make a partial delivery of 50 iMacs and you Invoice them. This means you invoice 80.000€ you in sale order left 50 iMacs to delivery and 80.000€ to invoice.

Now imagine you have hundreds of sale orders, result is that information given in sale order differs of the real price amount of sale orders that you will invoice. As you see thousands of euros for invoicing but really not because you have already sent an invoice some most of them.

Very thanks for opinions

Regards

**Comment by elicoidal** [comment]
Back in version 6, we had the progress bars (delivered and invoiced) which was nice. We have a module for that in v7 AFAIK this or a simple percentage can be a good idea to follow up the progress of your SO.

**Comment by rafaelbn** [comment]
Hello @OCA/crm-sales-marketing-maintainers, could you give me you point of view here please? Thanks

**Comment by rafaelbn** [comment]
Thanks @elicoidal . I also discuss with @pedrobaeza and I'm closing this question in this moment while we check what's going on  in v9 a master.
