### ISSUE TITLE
[12.0] Fail to use sale_layout_category_hide_detail

### ISSUE THREAD

**Issue by Danoolo** [OCA/sale-reporting#88]
Hi guys, i installed the sale_layout_category_hide_detail module in a 12.0 instance and it was fine but when i tried to open a sale order got an error in js file sale_layout_category_hide_detail.js:

var SectionAndNoteListRenderer = {
        _renderBodyCell: function (record, node, index, options) {
            var $cell = this._super.apply(this, arguments);

            var options = this.state.fieldsInfo.list[node.attrs.name].options;
            var show_in_line_section = options.show_in_line_section;

            var isSection = record.data.display_type === 'line_section';
            var isNote = record.data.display_type === 'line_note';
            if (isSection || isNote) {
                if (show_in_line_section) {
                    return $cell.removeClass('o_hidden');

And the error wizard in odoo shows that attribute option does not exist. Also get this error in browser console: 

web.assets_backend.js:3234 Could not get content for /delivery/static/src/js/hide_details_translations.js defined in bundle 'web.assets_backend'.

And this errors only comes with this module installation. Checking the runbot oca instances for this module only get the second error but not the first one. Any help for this? thanks so much!

**Comment by pedrobaeza** [comment]
Please check with #87, and if not, there should be a third module that is conflicting with this one. Check in runbot if you can reproduce the same problem.
